services:
  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
    env_file:
      - .env
    image: mysql:8.0
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - leaving-match_network

  api:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    container_name: ${BACKEND_CONTAINER_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: "${DB_PORT}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    networks:
      - leaving-match_network

volumes:
  db-data:


networks:
  leaving-match_network:
    driver: bridge
