@baseURL= http://localhost:8085


### Recommended_Data
### 帰宅推奨時刻の登録（IDをバックエンドのに直す必要がある）（respocseはID,status）
POST {{baseURL}}/api/recommended?time=1175&member=1&member=2

### 最新の帰宅推奨時刻のstatus取得
GET {{baseURL}}/api/recommended/latest/status
### 最新の帰宅推奨時刻の対象メンバのID取得
GET {{baseURL}}/api/recommended/latest/members


### BusTime_Data
### 推奨バスの時刻の登録
POST {{baseURL}}/api/bustime/1?previous=1160&nearest=1170&next=1180

### 一覧orIDに対応するカラムの取得
GET {{baseURL}}/api/bustime/2
### 最新のカラム取得
GET {{baseURL}}/api/bustime/latest


### Vote_Data
### 投票情報の登録(slack_user_id=2)
POST {{baseURL}}/api/vote/1?vote=previous,nearest

### 投票結果の取得
GET {{baseURL}}/api/vote/1


### Result_Data
### 投票後選ばれたバスの時刻の登録(bustime_id=1)
POST {{baseURL}}/api/result/1

### 投票結果の取得(bustime_id=1)
GET {{baseURL}}/api/result/1
###
GET {{baseURL}}/api/result/latest


### User_Data
### ユーザ情報の登録（staywatch、name、slackのいずれか）
POST {{baseURL}}/api/user?staywatch=1&name=kaji

### 不足情報の上書き(backend_user_id=1)
PUT {{baseURL}}/api/user/1?slack=1

### ユーザ情報の検索（backend, staywatch、name、slackのいずれか）
GET {{baseURL}}/api/user?staywatch=1