@baseURL= http://localhost:8085


### BusTime_Data
### 推奨バスの時刻の登録
POST {{baseURL}}/api/bustime?previous=1170&nearest=1200&next=1230

### 一覧の取得（フロント側で最新に絞ったりフィルタかける）
GET {{baseURL}}/api/bustime?id=1


### 対象メンバの退室予測時刻
POST {{baseURL}}/api/prediction/1/1?time=1170

### BusTimeIDに対応する対象メンバ複数人の取得(カラム数で対象メンバの数も取得できる)
GET {{baseURL}}/api/prediction/1


### Vote_Data
### 投票情報の登録(bustime_id=1,user_id=2)
POST {{baseURL}}/api/vote/1/2?vote=previous,nearest

### 投票結果の取得
GET {{baseURL}}/api/vote/1


### Result_Data
### 投票後選ばれたバスの時刻の登録(bustime_id=1)
POST {{baseURL}}/api/result/1

### 投票結果の取得
GET {{baseURL}}/api/result
###
GET {{baseURL}}/api/result?id=1